FROM python:3.9

# Prevent Python from writing .pyc files and enable unbuffered logging
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

# Install dependencies
COPY django-helloworld/requirements.txt /code/
RUN pip install -r requirements.txt

# Copy the Django project files
COPY django-helloworld /code/

# Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
